const stories = [
  {
    id: 1,
    title: "The Tortoise and the Birds",
    language: "English",
    audio: "/audio/tortoise.mp3",
    text: "Once upon a time, the tortoise wanted to fly with the birds. The birds agreed to help him, but the tortoise had a trick up his sleeve. He convinced each bird to lend him a feather, forming a beautiful set of wings. But once in the sky, he claimed all the food at the feast was meant for him. The birds, angered by his greed, took back their feathers, leaving him to fall from the sky. He landed on his shell, which cracked, giving tortoises their rough shells today.",
    image: "/images/tortoise.jpg",
    choices: [],
  },
  {
    id: 1,
    title: "Ijapa ati Awọn Ẹyẹ",
    language: "Yoruba",
    audio: "/audio/tortoise_yo.mp3",
    text: "Lẹ́yìn ọjọ kan, ijapa fẹ́ fo pẹ̀lú àwọn ẹyẹ. Àwọn ẹyẹ gbà pé wọn yoo ran án lọ́wọ́, ṣùgbọ́n ijapa ní àṣẹ̀ṣẹ̀ kan...",
    image: "/images/tortoise.jpg",
    choices: [
      { text: "Fo pẹ̀lú àwọn ẹyẹ", next: 2 },
      { text: "Duro lórí ilẹ̀", next: 3 },
    ],
  },
  {
    id: 2,
    title: "Anansi the Spider",
    language: "English",
    audio: "/audio/anansi.mp3",
    text: "Anansi the spider was known for his cunning and trickery. One day, he decided to outsmart the entire village. He tricked them into giving him all their wisdom, which he stored in a pot. But when trying to hide it, he stumbled and spilled it, scattering wisdom across the land. Since then, wisdom has been shared among all people instead of belonging to just one person.",
    image: "/images/anansi.jpg",
    choices: [],
  },
  {
    id: 2,
    title: "Anansi the Spider",
    language: "Pidgin",
    audio: "/audio/anansi_pg.mp3",
    text: "Anansi na spider wey sabi do wayo well well. One day, e decide to use im sense beat everybody for village...",
    image: "/images/anansi.jpg",
    choices: [
      { text: "Do wayo for the people", next: 4 },
      { text: "Help dem", next: 5 },
    ],
  },
  {
    id: 3,
    title: "The Lion and the Mouse",
    language: "English",
    audio: "/audio/lion.mp3",
    text: "A tiny mouse once saved a mighty lion from a hunter’s trap. The lion learned that even the smallest creatures can be of great help. Grateful, the lion declared that from that day on, no lion would harm a mouse. The two became unlikely friends, and the lion kept his promise, protecting small creatures in his kingdom.",
    image: "/images/lion.jpg",
    choices: [],
  },
  {
    id: 3,
    title: "Zaki da Kurege",
    language: "Hausa",
    audio: "/audio/lion_ha.mp3",
    text: "Wani karamin kurege ya ceci babban zaki daga tarko. Zaki ya koyi cewa ko da ƙanana na iya taimakawa...",
    image: "/images/lion.jpg",
    choices: [
      { text: "Taimaka wa zaki", next: 6 },
      { text: "Yi watsi da zaki", next: 7 },
    ],
  },
  {
    id: 4,
    title: "The King’s Drum",
    language: "English",
    audio: "/audio/drum.mp3",
    text: "The king’s drum was a magical instrument that could summon rain. One day, it was stolen by a jealous rival. The villagers, with the help of a wise elder, tricked the rival into playing the drum at the wrong time, revealing his theft. The drum was returned to the king, and rain blessed the land once again.",
    image: "/images/drum.jpg",
    choices: [],
  },
  {
    id: 4,
    title: "Ududo Na Ekwu",
    language: "Igbo",
    audio: "/audio/drum_ig.mp3",
    text: "Ndị mmadụ n’abụghị ịhụ̀ drum eze, na-achọ̀ ya. Otu ụbọchị, onye iro were ya...",
    image: "/images/drum.jpg",
    choices: [
      { text: "Chọọ drum ahụ", next: 8 },
      { text: "Jụọ chi maka enyemaka", next: 9 },
    ],
  },
  {
    id: 5,
    title: "The Magic Calabash",
    language: "English",
    audio: "/audio/calabash.mp3",
    text: "A young girl found a magic calabash that could produce endless food. But she had to be careful not to misuse its power. One day, she forgot the magic words to stop it, and the food overflowed, covering the village. With the help of an elder, she remembered the words just in time. The village learned to use the calabash wisely, ensuring no one ever went hungry again.",
    image: "/images/calabash.jpg",
    choices: [],
  },
  {
    id: 5,
    title: "Taba Buta Mai Sihiri",
    language: "Hausa",
    audio: "/audio/calabash_ha.mp3",
    text: "Wata yarinya ta gano taba buta da ke samar da abinci ba ƙarewa. Amma dole ne ta yi hankali kada ta yi amfani da ita ba daidai ba...",
    image: "/images/calabash.jpg",
    choices: [
      { text: "Raba abinci", next: 10 },
      { text: "Rike sirri", next: 11 },
    ],
  },
  {
    id: 6,
    title: "The Brave Hunter",
    language: "English",
    audio: "/audio/hunter.mp3",
    text: "A brave hunter once saved his village from a ferocious lion. But the lion had a secret that changed everything. It was protecting its cubs from an even greater danger—poachers. The hunter, moved by the lion’s plight, helped it find a safer home, and the two became legends in the land.",
    image: "/images/hunter.jpg",
    choices: [],
  },
  {
    id: 6,
    title: "Olú ọdẹ tó gbóná",
    language: "Yoruba",
    audio: "/audio/hunter_yo.mp3",
    text: "Olú ọdẹ kan gbà ìlú rẹ̀ là kúrò lọ́wọ́ ọdẹ. Ṣùgbọ́n ọdẹ náà ní ìhòrí kan tó yí padà gbogbo nǹkan...",
    image: "/images/hunter.jpg",
    choices: [
      { text: "Jà lọ́dọ̀ ọdẹ", next: 12 },
      { text: "Ṣe ọ̀rẹ́ pẹ̀lú ọdẹ", next: 13 },
    ],
  },
  {
    id: 7,
    title: "The Clever Rabbit",
    language: "English",
    audio: "/audio/rabbit.mp3",
    text: "A clever rabbit outsmarted a greedy lion by using his wits. The lion learned that brains are better than brawn. Defeated, the lion promised never to underestimate small creatures again. The rabbit, now a hero, lived happily, teaching others the power of intelligence.",
    image: "/images/rabbit.jpg",
    choices: [],
  },
  {
    id: 7,
    title: "Ehoro Olóye",
    language: "Yoruba",
    audio: "/audio/rabbit_yo.mp3",
    text: "Ehoro kan fi ogbón rẹ̀ ṣẹ́ ọdẹ. Ọdẹ náà kọ́kọ́ rí i pé ogbón ju agbára lọ...",
    image: "/images/rabbit.jpg",
    choices: [
      { text: "Ṣe àṣẹ̀ṣẹ̀ fún ọdẹ", next: 14 },
      { text: "Sá lọ", next: 15 },
    ],
  },
  {
    id: 8,
    title: "The Talking Drum",
    language: "English",
    audio: "/audio/talking-drum.mp3",
    text: "A talking drum could communicate messages across villages. One day, it helped prevent a war. A misunderstanding between two chiefs nearly led to battle, but the drum spread the truth before swords were drawn. The chiefs reconciled, and the drum became a symbol of peace.",
    image: "/images/drum2.jpg",
    choices: [],
  },
  {
    id: 8,
    title: "Gangan Aláṣọ̀rọ̀",
    language: "Yoruba",
    audio: "/audio/talking-drum_yo.mp3",
    text: "Gangan kan lè ṣe àṣẹ̀ṣẹ̀ láti fi ìròyìn ránṣẹ́ sí àwọn ìlú. Lọ́jọ́ kan, ó ṣèrànwọ́ láti dẹ́kun ogun...",
    image: "/images/drum2.jpg",
    choices: [
      { text: "Lo gangan láti ránṣẹ́", next: 16 },
      { text: "Fi gangan sí i pamo", next: 17 },
    ],
  },
  {
    id: 9,
    title: "The Tree of Life",
    language: "English",
    audio: "/audio/tree.mp3",
    text: "A sacred tree held the wisdom of the ancestors. Villagers sought its guidance but had to pass a test of character before they could receive its wisdom.",
    image: "/images/tree.jpg",
    choices: [],
  },
  {
    id: 9,
    title: "Osisi Ndụ",
    language: "Igbo",
    audio: "/audio/tree_ig.mp3",
    text: "Osisi dị nsọ nwere amamihe nke ndị nna ochie. A sịrị na onye ọ bụla nwere ike ịza ilu ya ga-enweta nnukwu ihe ọmụma. Otu nwatakịrị, kpebisiri ike inyere obodo ya aka, doziri ilu osisi ahụ wee weta ọganihu nye ndị ya.",
    image: "/images/tree.jpg",
    choices: [],
  },
  {
    id: 10,
    title: "The Eagle and the Chick",
    language: "English",
    audio: "/audio/eagle.mp3",
    text: "An eagle and a chick became unlikely friends, teaching the world that strength and kindness can coexist.",
    image: "/images/eagle.jpg",
    choices: [],
  },
  {
    id: 10,
    title: "Idi ati Ọkụkọ",
    language: "Yoruba",
    audio: "/audio/eagle.mp3",
    text: "An eagle and a chick became unlikely friends...",
    image: "/images/eagle.jpg",
    choices: [],
  },
  {
    id: 11,
    title: "The Hunter and the Enchanted Deer",
    language: "English",
    audio: "/audio/deer.mp3",
    text: "A hunter encountered a mystical deer that led him to a hidden treasure but at a great moral cost.",
    image: "/images/deer.jpg",
    choices: [],
  },
  {
    id: 11,
    title: "The Hunter and the Enchanted Deer",
    language: "Hausa",
    audio: "/audio/deer.mp3",
    text: "A hunter encountered a mystical deer...",
    image: "/images/deer.jpg",
    choices: [],
  },
  {
    id: 12,
    title: "The Fox and the Drum",
    language: "Pidgin",
    audio: "/audio/foxdrum.mp3",
    text: "Fox think say e get sense, but e go learn...",
    image: "/images/fox.jpg",
    choices: [],
  },
  {
    id: 12,
    title: "The Fox and the Drum",
    language: "English",
    audio: "/audio/foxdrum.mp3",
    text: "A cunning fox learned a hard lesson when he tried to steal a drum that wasn’t his to take.",
    image: "/images/fox.jpg",
    choices: [],
  },
  {
    id: 13,
    title: "The River Spirit’s Gift",
    language: "English",
    audio: "/audio/river.mp3",
    text: "A fisherman received a gift from the river spirit that tested his patience and greed.",
    image: "/images/river.jpg",
    choices: [],
  },
  {
    id: 13,
    title: "The River Spirit’s Gift",
    language: "Efik",
    audio: "/audio/river.mp3",
    text: "A fisherman received a gift from the river spirit...",
    image: "/images/river.jpg",
    choices: [],
  },
  {
    id: 14,
    title: "The Talking Skull",
    language: "English",
    audio: "/audio/skull.mp3",
    text: "A man found a skull that could talk...",
    image: "/images/skull.jpg",
    choices: [],
  },
  {
    id: 14,
    title: "The Talking Skull",
    language: "Igbo",
    audio: "/audio/skull.mp3",
    text: "A man found a skull that could talk...",
    image: "/images/skull.jpg",
    choices: [],
  },
  {
    id: 15,
    title: "The Woman Who Refused to Share",
    language: "English",
    audio: "/audio/woman.mp3",
    text: "A woman’s greed nearly destroyed her village...",
    image: "/images/woman.jpg",
    choices: [],
  },
  {
    id: 15,
    title: "The Woman Who Refused to Share",
    language: "Tiv",
    audio: "/audio/woman.mp3",
    text: "A woman’s greed nearly destroyed her village...",
    image: "/images/woman.jpg",
    choices: [],
  },
  {
    id: 16,
    title: "How the Sun and Moon Came to Be",
    language: "English",
    audio: "/audio/sunmoon.mp3",
    text: "Long ago, the sun and moon lived on Earth...",
    image: "/images/sunmoon.jpg",
    choices: [],
  },
  {
    id: 16,
    title: "How the Sun and Moon Came to Be",
    language: "Yoruba",
    audio: "/audio/sunmoon.mp3",
    text: "Long ago, the sun and moon lived on Earth and...",
    image: "/images/sunmoon.jpg",
    choices: [],
  },
  {
    id: 17,
    title: "The Elephant and the Tortoise",
    language: "English",
    audio: "/audio/elephant.mp3",
    text: "The elephant and the tortoise had a race to determine who was the strongest. The tortoise, using his wit, tricked the elephant into losing the race.",
    image: "/images/elephant.jpg",
    choices: [],
  },
  {
    id: 17,
    title: "Ení àti Ìjàpá",
    language: "Yoruba",
    audio: "/audio/elephant_yo.mp3",
    text: "Ení àti ìjàpá fẹ́ ṣe ìdíje láti mọ̀ ẹni tí ó lágbára jù. Ìjàpá, ní lílo ogbón rẹ̀, ṣe àṣẹ̀ṣẹ̀ fún ení láti padà ní ìdíje náà.",
    image: "/images/elephant.jpg",
    choices: [],
  },
  {
    id: 18,
    title: "The Magic Pot",
    language: "English",
    audio: "/audio/pot.mp3",
    text: "A magic pot could produce endless food, but it came with a warning: misuse it, and it would disappear forever.",
    image: "/images/pot.jpg",
    choices: [],
  },
  {
    id: 18,
    title: "Itẹ Sihiri",
    language: "Yoruba",
    audio: "/audio/pot_yo.mp3",
    text: "Itẹ sihiri lè ṣe àwọn ounjẹ tí kò ní òpin, ṣùgbọ́n ó ní ìkìlọ̀: bí o bá lò ó bàjẹ́, ó máa fọ́nú fò.",
    image: "/images/pot.jpg",
    choices: [],
  },
  {
    id: 19,
    title: "The Wise Crab",
    language: "English",
    audio: "/audio/crab.mp3",
    text: "A wise crab helped a village solve a mystery that had plagued them for years, teaching them the value of patience and observation.",
    image: "/images/crab.jpg",
    choices: [],
  },
  {
    id: 19,
    title: "Ọ̀gbọ̀n Ọ̀gbọ̀n",
    language: "Yoruba",
    audio: "/audio/crab_yo.mp3",
    text: "Ọ̀gbọ̀n kan ṣèrànwọ́ fún ìlú kan láti yanjú ìṣòro kan tí ó ti pẹ́ fún ọdún púpọ̀, kí ó lè kọ́ wọn nípa ànífáyègẹ́ àti ìṣọ̀tẹ̀.",
    image: "/images/crab.jpg",
    choices: [],
  },
  {
    id: 20,
    title: "The Singing Stone",
    language: "English",
    audio: "/audio/stone.mp3",
    text: "A singing stone brought joy to a village, but only those with pure hearts could hear its melody.",
    image: "/images/stone.jpg",
    choices: [],
  },
  {
    id: 20,
    title: "Òkúta Orin",
    language: "Yoruba",
    audio: "/audio/stone_yo.mp3",
    text: "Òkúta orin mú ìdùnnú wá sí ìlú kan, ṣùgbọ́n àwọn tí ó ní ọkàn mímọ́ ló lè gbọ́ orin rẹ̀.",
    image: "/images/stone.jpg",
    choices: [],
  },
  {
    id: 21,
    title: "The Enchanted Fish",
    language: "English",
    audio: "/audio/fish.mp3",
    text: "A fisherman caught a talking fish that promised him endless riches if he let it go. But his greed got the best of him, and he tried to catch it again. The fish vanished forever, and the fisherman was left with nothing.",
    image: "/images/fish.jpg",
    choices: [],
  },
  {
    id: 21,
    title: "Kifi Mai Magana",
    language: "Hausa",
    audio: "/audio/fish_ha.mp3",
    text: "Wani mai kamun kifi ya samu wani kifi mai magana wanda ya yi alkawari zai ba shi arziki idan ya sake shi...",
    image: "/images/fish.jpg",
    choices: [
      { text: "Sake kifi", next: 22 },
      { text: "Kama kifi", next: 23 },
    ],
  },
  {
    id: 22,
    title: "The Giant’s Secret",
    language: "English",
    audio: "/audio/giant.mp3",
    text: "A kind-hearted giant had a secret garden where magical fruits grew. When a selfish king tried to steal them, the giant taught him a lesson about kindness.",
    image: "/images/giant.jpg",
    choices: [],
  },
  {
    id: 22,
    title: "Asiri Olókè",
    language: "Yoruba",
    audio: "/audio/giant_yo.mp3",
    text: "Olókè kan tí ó ní ọ̀gbìn àṣẹ̀ṣẹ̀ tí ó súnkẹrẹ gbígbì ti wọn kò gbọ́...",
    image: "/images/giant.jpg",
    choices: [
      { text: "Ṣàbẹ̀wò sí ọ̀gbìn náà", next: 24 },
      { text: "Dákẹ́ kí o má ṣe wi", next: 25 },
    ],
  },
  {
    id: 23,
    title: "The Moonlit Dance",
    language: "English",
    audio: "/audio/dance.mp3",
    text: "Every full moon, the spirits of the forest gathered to dance. A curious boy once joined them and discovered a secret that changed his life forever.",
    image: "/images/dance.jpg",
    choices: [],
  },
  {
    id: 23,
    title: "Egwu Anyanwụ",
    language: "Igbo",
    audio: "/audio/dance_ig.mp3",
    text: "Ọtụtụ afọ gara aga, mmụọ nke ọhịa na-eme emume ukwu n'oké ọhịa...",
    image: "/images/dance.jpg",
    choices: [
      { text: "Jikọta ha", next: 26 },
      { text: "Zoo anya", next: 27 },
    ],
  },
  {
    id: 24,
    title: "The Talking Drum",
    language: "English",
    audio: "/audio/drum.mp3",
    text: "A young boy found an enchanted drum that could speak. It gave him wisdom and helped him bring peace to his village.",
    image: "/images/drum.jpg",
    choices: [],
  },
  {
    id: 24,
    title: "Ìlù Aláyọ",
    language: "Yoruba",
    audio: "/audio/drum_yo.mp3",
    text: "Ọmọkùnrin kan rí ìlù tí ó le sọ̀rọ̀. Pẹ̀lú ìmòran ìlù yìí, ó ṣàkóso àlàáfíà ní abúlé wọn...",
    image: "/images/drum.jpg",
    choices: [
      { text: "Gbọ ohun ìlù", next: 28 },
      { text: "Fi ìlù sílẹ̀", next: 29 },
    ],
  },
  {
    id: 25,
    title: "The Clever Tortoise",
    language: "English",
    audio: "/audio/tortoise.mp3",
    text: "Tortoise tricked the animals into giving him all the food in the land, but his greed led to his downfall.",
    image: "/images/tortoise.jpg",
    choices: [],
  },
  {
    id: 25,
    title: "Mbekwu, Onye Amamihe",
    language: "Igbo",
    audio: "/audio/tortoise_ig.mp3",
    text: "Mbekwu gwara anụmanụ niile ka ha nye ya nri ha niile, mana ọ gbalịrị iweghara ihe niile...",
    image: "/images/tortoise.jpg",
    choices: [
      { text: "Gwa anụmanụ okwu", next: 30 },
      { text: "Zere nsogbu", next: 31 },
    ],
  },
  {
    id: 26,
    title: "The King’s Lost Crown",
    language: "English",
    audio: "/audio/crown.mp3",
    text: "A mischievous monkey stole the king’s crown, leading to an adventure through the jungle to retrieve it.",
    image: "/images/crown.jpg",
    choices: [],
  },
  {
    id: 26,
    title: "Ade Ọba Ti Sọnu",
    language: "Yoruba",
    audio: "/audio/crown_yo.mp3",
    text: "Àádọ́ta láti rí adé Ọba tó sọnu, ṣùgbọ́n àwọn ẹranko gbìyànjú láti fi tún un wá...",
    image: "/images/crown.jpg",
    choices: [
      { text: "Tẹ̀lé ògèdè", next: 32 },
      { text: "Pe àwọn olùṣọ́", next: 33 },
    ],
  },
  {
    id: 27,
    title: "The River Spirit’s Gift",
    language: "English",
    audio: "/audio/river.mp3",
    text: "A girl who showed kindness to the river spirit was rewarded with an endless supply of water during a drought.",
    image: "/images/river.jpg",
    choices: [],
  },
  {
    id: 27,
    title: "Ẹ̀bùn Ẹ̀mí Odo",
    language: "Yoruba",
    audio: "/audio/river_yo.mp3",
    text: "Omodebinrin kan ti o fi ife han ẹ̀mí odo ri ebun pataki to pa ebi rẹ run...",
    image: "/images/river.jpg",
    choices: [
      { text: "Ṣeun fun ẹ̀mí odo", next: 34 },
      { text: "Kuro l’odo", next: 35 },
    ],
  },
  {
    id: 28,
    title: "The Enchanted Flute",
    language: "English",
    audio: "/audio/flute.mp3",
    text: "A boy discovers a magical flute that can summon animals and bring harmony to the forest.",
    image: "/images/flute.jpg",
    choices: [],
  },
  {
    id: 28,
    title: "Okike Opi",
    language: "Igbo",
    audio: "/audio/flute_ig.mp3",
    text: "Nwa nwoke chọtara opi anwansi nke na-akpọ anụmanụ wee mee ka udo dị n’ime ọhịa.",
    image: "/images/flute.jpg",
    choices: [
      { text: "Gwuo opi", next: 36 },
      { text: "Zoo opi", next: 37 },
    ],
  },
  {
    id: 29,
    title: "The Firefly’s Secret",
    language: "English",
    audio: "/audio/firefly.mp3",
    text: "A curious child follows a firefly deep into the forest and uncovers an ancient secret.",
    image: "/images/firefly.jpg",
    choices: [],
  },
  {
    id: 29,
    title: "Àṣírí Iná Iná",
    language: "Yoruba",
    audio: "/audio/firefly_yo.mp3",
    text: "Ọmọde kan tẹ̀lé iná iná wọ igbo, ó sì rí àṣírí ìgbàanì kan.",
    image: "/images/firefly.jpg",
    choices: [
      { text: "Tẹ̀lé iná iná", next: 38 },
      { text: "Dàbọ̀", next: 39 },
    ],
  },
  {
    id: 30,
    title: "The Kind Leopard",
    language: "English",
    audio: "/audio/leopard.mp3",
    text: "A kind leopard helps a lost traveler find his way home, but asks for a promise in return.",
    image: "/images/leopard.jpg",
    choices: [],
  },
  {
    id: 30,
    title: "Ekènye Ọnụ",
    language: "Igbo",
    audio: "/audio/leopard_ig.mp3",
    text: "Agụ mara obi ebere nyere onye njem ụzọ, mana ọ rịọrọ nkwa n’aka ya.",
    image: "/images/leopard.jpg",
    choices: [
      { text: "Mee nkwa", next: 40 },
      { text: "Jụ nkwa", next: 41 },
    ],
  },
  {
    id: 31,
    title: "The Farmer and the Talking Yam",
    language: "English",
    audio: "/audio/yam.mp3",
    text: "A farmer is shocked when his yam starts talking, leading to a hilarious adventure.",
    image: "/images/yam.jpg",
    choices: [],
  },
  {
    id: 31,
    title: "Agbẹ àti Ìṣú Aláyọ",
    language: "Yoruba",
    audio: "/audio/yam_yo.mp3",
    text: "Agbẹ kan yàà jẹ́rìí pe ìṣú rẹ̀ ń sọ̀rọ̀, ó sì mú irin-ajo ẹlẹrin kikan.",
    image: "/images/yam.jpg",
    choices: [
      { text: "Béèrè lọ́wọ́ ìṣú", next: 42 },
      { text: "Fi ìṣú sílẹ̀", next: 43 },
    ],
  },
  {
    id: 32,
    title: "The Fisherman’s Fortune",
    language: "English",
    audio: "/audio/fisherman.mp3",
    text: "A poor fisherman saves a magical fish and is granted three wishes.",
    image: "/images/fisherman.jpg",
    choices: [],
  },
  {
    id: 32,
    title: "Ori Omi Aláyọ",
    language: "Yoruba",
    audio: "/audio/fisherman_yo.mp3",
    text: "Apẹjà kan gbà ẹja àlàyé kan là, ó sì fun un ni àǹfàní mẹ́ta.",
    image: "/images/fisherman.jpg",
    choices: [
      { text: "Fi àǹfàní kọfẹ́", next: 44 },
      { text: "Lò àǹfàní", next: 45 },
    ],
  },
];

export default stories;
