const stories = [
  {
    id: 1,
    title: "The Tortoise and the Birds",
    language: "English",
    audio: "/audio/tortoise.mp3",
    text: "Once upon a time, the tortoise wanted to fly with the birds. The birds agreed to help him, but the tortoise had a trick up his sleeve. He convinced each bird to lend him a feather, forming a beautiful set of wings. But once in the sky, he claimed all the food at the feast was meant for him. The birds, angered by his greed, took back their feathers, leaving him to fall from the sky. He landed on his shell, which cracked, giving tortoises their rough shells today.",
    image: "/images/tortoise.jpg",
    choices: [],
  },
  {
    id: 1,
    title: "Ijapa ati Awọn Ẹyẹ",
    language: "Yoruba",
    audio: "/audio/tortoise_yo.mp3",
    text: "Lẹ́yìn ọjọ kan, ijapa fẹ́ fo pẹ̀lú àwọn ẹyẹ. Àwọn ẹyẹ gbà pé wọn yoo ran án lọ́wọ́, ṣùgbọ́n ijapa ní àṣẹ̀ṣẹ̀ kan...",
    image: "/images/tortoise.jpg",
    choices: [
      { text: "Fo pẹ̀lú àwọn ẹyẹ", next: 2 },
      { text: "Duro lórí ilẹ̀", next: 3 },
    ],
  },
  {
    id: 2,
    title: "Anansi the Spider",
    language: "English",
    audio: "/audio/anansi.mp3",
    text: "Anansi the spider was known for his cunning and trickery. One day, he decided to outsmart the entire village. He tricked them into giving him all their wisdom, which he stored in a pot. But when trying to hide it, he stumbled and spilled it, scattering wisdom across the land. Since then, wisdom has been shared among all people instead of belonging to just one person.",
    image: "/images/anansi.jpg",
    choices: [],
  },
  {
    id: 2,
    title: "Anansi the Spider",
    language: "Pidgin",
    audio: "/audio/anansi_pg.mp3",
    text: "Anansi na spider wey sabi do wayo well well. One day, e decide to use im sense beat everybody for village...",
    image: "/images/anansi.jpg",
    choices: [
      { text: "Do wayo for the people", next: 4 },
      { text: "Help dem", next: 5 },
    ],
  },
  {
    id: 3,
    title: "The Lion and the Mouse",
    language: "English",
    audio: "/audio/lion.mp3",
    text: "A tiny mouse once saved a mighty lion from a hunter’s trap. The lion learned that even the smallest creatures can be of great help. Grateful, the lion declared that from that day on, no lion would harm a mouse. The two became unlikely friends, and the lion kept his promise, protecting small creatures in his kingdom.",
    image: "/images/lion.jpg",
    choices: [],
  },
  {
    id: 3,
    title: "Zaki da Kurege",
    language: "Hausa",
    audio: "/audio/lion_ha.mp3",
    text: "Wani karamin kurege ya ceci babban zaki daga tarko. Zaki ya koyi cewa ko da ƙanana na iya taimakawa...",
    image: "/images/lion.jpg",
    choices: [
      { text: "Taimaka wa zaki", next: 6 },
      { text: "Yi watsi da zaki", next: 7 },
    ],
  },
  {
    id: 4,
    title: "The King’s Drum",
    language: "English",
    audio: "/audio/drum.mp3",
    text: "The king’s drum was a magical instrument that could summon rain. One day, it was stolen by a jealous rival. The villagers, with the help of a wise elder, tricked the rival into playing the drum at the wrong time, revealing his theft. The drum was returned to the king, and rain blessed the land once again.",
    image: "/images/drum.jpg",
    choices: [],
  },
  {
    id: 4,
    title: "Ududo Na Ekwu",
    language: "Igbo",
    audio: "/audio/drum_ig.mp3",
    text: "Ndị mmadụ n’abụghị ịhụ̀ drum eze, na-achọ̀ ya. Otu ụbọchị, onye iro were ya...",
    image: "/images/drum.jpg",
    choices: [
      { text: "Chọọ drum ahụ", next: 8 },
      { text: "Jụọ chi maka enyemaka", next: 9 },
    ],
  },
  {
    id: 5,
    title: "The Magic Calabash",
    language: "English",
    audio: "/audio/calabash.mp3",
    text: "A young girl found a magic calabash that could produce endless food. But she had to be careful not to misuse its power. One day, she forgot the magic words to stop it, and the food overflowed, covering the village. With the help of an elder, she remembered the words just in time. The village learned to use the calabash wisely, ensuring no one ever went hungry again.",
    image: "/images/calabash.jpg",
    choices: [],
  },
  {
    id: 5,
    title: "Taba Buta Mai Sihiri",
    language: "Hausa",
    audio: "/audio/calabash_ha.mp3",
    text: "Wata yarinya ta gano taba buta da ke samar da abinci ba ƙarewa. Amma dole ne ta yi hankali kada ta yi amfani da ita ba daidai ba...",
    image: "/images/calabash.jpg",
    choices: [
      { text: "Raba abinci", next: 10 },
      { text: "Rike sirri", next: 11 },
    ],
  },
  {
    id: 6,
    title: "The Brave Hunter",
    language: "English",
    audio: "/audio/hunter.mp3",
    text: "A brave hunter once saved his village from a ferocious lion. But the lion had a secret that changed everything. It was protecting its cubs from an even greater danger—poachers. The hunter, moved by the lion’s plight, helped it find a safer home, and the two became legends in the land.",
    image: "/images/hunter.jpg",
    choices: [],
  },
  {
    id: 6,
    title: "Olú ọdẹ tó gbóná",
    language: "Yoruba",
    audio: "/audio/hunter_yo.mp3",
    text: "Olú ọdẹ kan gbà ìlú rẹ̀ là kúrò lọ́wọ́ ọdẹ. Ṣùgbọ́n ọdẹ náà ní ìhòrí kan tó yí padà gbogbo nǹkan...",
    image: "/images/hunter.jpg",
    choices: [
      { text: "Jà lọ́dọ̀ ọdẹ", next: 12 },
      { text: "Ṣe ọ̀rẹ́ pẹ̀lú ọdẹ", next: 13 },
    ],
  },
  {
    id: 7,
    title: "The Clever Rabbit",
    language: "English",
    audio: "/audio/rabbit.mp3",
    text: "A clever rabbit outsmarted a greedy lion by using his wits. The lion learned that brains are better than brawn. Defeated, the lion promised never to underestimate small creatures again. The rabbit, now a hero, lived happily, teaching others the power of intelligence.",
    image: "/images/rabbit.jpg",
    choices: [],
  },
  {
    id: 7,
    title: "Ehoro Olóye",
    language: "Yoruba",
    audio: "/audio/rabbit_yo.mp3",
    text: "Ehoro kan fi ogbón rẹ̀ ṣẹ́ ọdẹ. Ọdẹ náà kọ́kọ́ rí i pé ogbón ju agbára lọ...",
    image: "/images/rabbit.jpg",
    choices: [
      { text: "Ṣe àṣẹ̀ṣẹ̀ fún ọdẹ", next: 14 },
      { text: "Sá lọ", next: 15 },
    ],
  },
  {
    id: 8,
    title: "The Talking Drum",
    language: "English",
    audio: "/audio/talking-drum.mp3",
    text: "A talking drum could communicate messages across villages. One day, it helped prevent a war. A misunderstanding between two chiefs nearly led to battle, but the drum spread the truth before swords were drawn. The chiefs reconciled, and the drum became a symbol of peace.",
    image: "/images/drum2.jpg",
    choices: [],
  },
  {
    id: 8,
    title: "Gangan Aláṣọ̀rọ̀",
    language: "Yoruba",
    audio: "/audio/talking-drum_yo.mp3",
    text: "Gangan kan lè ṣe àṣẹ̀ṣẹ̀ láti fi ìròyìn ránṣẹ́ sí àwọn ìlú. Lọ́jọ́ kan, ó ṣèrànwọ́ láti dẹ́kun ogun...",
    image: "/images/talking-drum.jpg",
    choices: [
      { text: "Lo gangan láti ránṣẹ́", next: 16 },
      { text: "Fi gangan sí i pamo", next: 17 },
    ],
  },
  {
    id: 9,
    title: "The Tree of Life",
    language: "English",
    audio: "/audio/tree.mp3",
    text: "A sacred tree held the wisdom of the ancestors...",
    image: "/images/tree.jpg",
    choices: [],
  },
  {
    id: 9,
    title: "The Tree of Life",
    language: "Igbo",
    audio: "/audio/tree.mp3",
    text: "A sacred tree held the wisdom of the ancestors...",
    image: "/images/tree.jpg",
    choices: [],
  },
  {
    id: 10,
    title: "The Eagle and the Chick",
    language: "English",
    audio: "/audio/eagle.mp3",
    text: "An eagle and a chick became unlikely friends...",
    image: "/images/eagle.jpg",
    choices: [],
  },
  {
    id: 10,
    title: "The Eagle and the Chick",
    language: "Yoruba",
    audio: "/audio/eagle.mp3",
    text: "An eagle and a chick became unlikely friends...",
    image: "/images/eagle.jpg",
    choices: [],
  },
  {
    id: 11,
    title: "The Hunter and the Enchanted Deer",
    language: "English",
    audio: "/audio/deer.mp3",
    text: "A hunter encountered a mystical deer...",
    image: "/images/deer.jpg",
    choices: [],
  },
  {
    id: 11,
    title: "The Hunter and the Enchanted Deer",
    language: "Hausa",
    audio: "/audio/deer.mp3",
    text: "A hunter encountered a mystical deer...",
    image: "/images/deer.jpg",
    choices: [],
  },
  {
    id: 12,
    title: "The Fox and the Drum",
    language: "English",
    audio: "/audio/foxdrum.mp3",
    text: "Fox think say e get sense, but e go learn...",
    image: "/images/fox.jpg",
    choices: [],
  },
  {
    id: 12,
    title: "The Fox and the Drum",
    language: "Pidgin",
    audio: "/audio/foxdrum.mp3",
    text: "Fox think say e get sense, but e go learn...",
    image: "/images/fox.jpg",
    choices: [],
  },
  {
    id: 13,
    title: "The River Spirit’s Gift",
    language: "English",
    audio: "/audio/river.mp3",
    text: "A fisherman received a gift from the river spirit...",
    image: "/images/river.jpg",
    choices: [],
  },
  {
    id: 13,
    title: "The River Spirit’s Gift",
    language: "Efik",
    audio: "/audio/river.mp3",
    text: "A fisherman received a gift from the river spirit...",
    image: "/images/river.jpg",
    choices: [],
  },
  {
    id: 14,
    title: "The Talking Skull",
    language: "English",
    audio: "/audio/skull.mp3",
    text: "A man found a skull that could talk...",
    image: "/images/skull.jpg",
    choices: [],
  },
  {
    id: 14,
    title: "The Talking Skull",
    language: "Igbo",
    audio: "/audio/skull.mp3",
    text: "A man found a skull that could talk...",
    image: "/images/skull.jpg",
    choices: [],
  },
  {
    id: 15,
    title: "The Woman Who Refused to Share",
    language: "English",
    audio: "/audio/woman.mp3",
    text: "A woman’s greed nearly destroyed her village...",
    image: "/images/woman.jpg",
    choices: [],
  },
  {
    id: 15,
    title: "The Woman Who Refused to Share",
    language: "Tiv",
    audio: "/audio/woman.mp3",
    text: "A woman’s greed nearly destroyed her village...",
    image: "/images/woman.jpg",
    choices: [],
  },
  {
    id: 16,
    title: "How the Sun and Moon Came to Be",
    language: "English",
    audio: "/audio/sunmoon.mp3",
    text: "Long ago, the sun and moon lived on Earth...",
    image: "/images/sunmoon.jpg",
    choices: [],
  },
  {
    id: 16,
    title: "How the Sun and Moon Came to Be",
    language: "Yoruba",
    audio: "/audio/sunmoon.mp3",
    text: "Long ago, the sun and moon lived on Earth...",
    image: "/images/sunmoon.jpg",
    choices: [],
  },
];

export default stories;
